//
//  Strings.swift
//  NetflixApp
//
//  Created by Mac on 09/12/22.
//

import UIKit

class Strings {
    static let shared: Strings = Strings()
    
    let privacy = "PRIVACY"
    let signin = "SIGN IN"
    let register = "Register"
    let submit = "Submit"
    let create = "Create"
    let regsignin = "Sign In"
    let forgot_password = "Forgot Password"
    let create_profile_name = "Enter profile name"
    let login = "Login"
    let email = "Email"
    let password = "Enter Password"
    let newpassword = "New Password"
    let confirmpassword = "Confirm Password"
    let Dob = "Date of Birth (Ex: 10-11-2022)"
    let getstarted = "GET STARTED"
    let infolabeltext = "Sign in is protrcted by Google reCAPTCHA to ensure  you're not a bot Learn more"
    let create_profile_label = "Please create a profile to continue"
    let error_title = "Error"
    let something_error_message = "Something went wrong"
    let doberrortitle = "Error in Dob"
    let doberrormessage = "Enter Dob in Correct Format Ex: 10-10-2020"
    let email_error_title = "Error in Email"
    let email_error_message = "Enter a vallid Email"
    let password_error_title = "Error in Password"
    let password_error_message = "Enter a vallid Password"
    let confirmpassword_error_title = "Error in confirmpassword"
    let confirmpassword_error_message = "recheck the Confirmpassword"
    let password_confirmpassword_error_title = "Password != Confirmpassword"
    let password_confirmpassword_error_message = "Recheck entered Password & Confirmpassword"
    let registration_failed = "User Already Registered"
    let login_success = "Login Done"
    let login_sucess_message = "Click Ok Continue"
    let login_failure_message = "Check Email & Password"
    let login_Wrongpassword = "Password Incorrect"
    let cheveronback = "chevron.left"
    let success = "Success"
    let Dobverified = "Successfully Verified Date of Birth"
    let dob_mismatch = "DoB Does not Match"
    let not_a_vallid_user = "User Not Registered"
    let success_Registration_title = "User Details registered"
    let success_Registration_message = "Login with your email & password"
    let update_newpassword = "New Password updated"
    let email_verified = "Email id Found update new details"
    let Who_is_watching = "Who's Watching?"
    let minimum_one_profile_must = "Minimum one profile is needed"
    let edit = "Edit"
    let mylistlabel = "My List"
    let play = "PLay"
    let info = "Info"
    let home_cat = "Home"
    let movies_cat = "Movies"
    let tvshows_cat = "Tvshows"
    let mylist_cat = "Mylist"
    let Home = "Home"
    let Search = "Search"
    let Account = "Account"
    let Settings = "Settings"
    let cancel = "Cancel"
    let appSettings = "App Settings"
    let manageProfiles = "Manage Profiles"
    let notifications = "Notifications"
    let devices = "Devices"
    let help = "Help"
    let signOut = "Sign Out"
    let version = "Version "
    let videoPlayback = "Video Playback"
    let mobileDataUsage = "Mobile Data Usage"
    let automatic = "Automatic"
    let wifiOnly = "Wi-Fi Only"
    let downloads = "Downloads"
    let smartDownloads = "Smart Downloads"
    let smartDownloadsCaption = "Completed downloads will be deleted and replaced with next episodes only on wi-fi"
    let videoQuality = "Video Quality"
    let standard = "Standard"
    let deleteAllDownloads = "Delete All Downloads"
    let about = "About"
    let internetSpeedTest = "Internet Speed Test"
    let privacyPolicy = "Privacy Policy"
    let download = "Download"
    let rate = "Rate"
    let share = "Share"
    
}
 
